@startuml
'https://plantuml.com/class-diagram

interface AccountService {
    +createAccount();
    +deposit();
    +withdrow();
    +addInterest();
}

abstract AccountServiceApplicationFactory{
    +{abstract}createAccount();
    +deposit();
    +withdrow();
    +addInterest();
    +getAllAccounts();
    +getAccount();
}



interface ProductFactory {
    +createAccount();
    +createNotifyer();
    +createInterest();
}
'new Account product with subclasses
abstract Account{
+getinterest
+getInterestState
+addInterest()
+deposit(double amount)
+withdraw(double amount)
+addEntry(AccountEntry entry)
+getCustomer()
+getAccountType()
}
class CheckingAccount
class SavingAccount


 abstract InterestCalculator{
 calcInterest()
 }
 class PersonalSavingInterestCalculator{
 calcInterest()
 }
 class PersonalCheckingInterestCalculator{
 calcInterest()
 }
 class CompanySavingInterestCalculator{
 calcInterest()
 }
 class CompanyCheckingInterestCalculator{
 calcInterest()
 }


 interface state{
 handleInterest()
 }

 class lowInterestState{
 handleInterest()
 }
 class midInterestState{
 handleInterest()
 }
 class highInterestState{
 handleInterest()
 }

'diagram
CheckingAccount --|> Account
SavingAccount --|> Account


'Observer pattern for notifiyer
interface Subject
Interface Observer
class EmailObserver

Observer --> Subject
EmailObserver ..|> Observer

AccountServiceApplicationFactory --> Subject


AccountServiceApplicationFactory ..|> AccountService
AccountServiceImpl --|> AccountServiceApplicationFactory
CCardServiceImpl --|> AccountServiceApplicationFactory

AccountServiceApplicationFactory ..> ProductFactory
Account <-- AccountServiceApplicationFactory

 Account -->InterestCalculator
Account --> state
  lowInterestState ..|> state
  midInterestState ..|> state
  highInterestState ..|> state
 InterestCalculator <|--PersonalSavingInterestCalculator
 InterestCalculator <|--PersonalCheckingInterestCalculator
 InterestCalculator <|--CompanySavingInterestCalculator
 InterestCalculator <|--CompanyCheckingInterestCalculator

@enduml