@startuml
'https://plantuml.com/class-diagram

interface AccountService {
    +createAccount();
    +deposit();
    +withdrow();
    +addInterest();
}

abstract AccountServiceApplicationFactory{
    +{abstract}createAccount();
    +deposit();
    +withdrow();
    +addInterest();
    +getAllAccounts();
    +getAccount();
}

interface StorageFactory {
    +createAccountDAO();
    +createCustomerDAO();
    +createAccountEntryDAO();
}
'new Account product with subclasses
abstract Account
class CheckingAccount
class SavingAccount
'diagram
CheckingAccount --|> Account
SavingAccount --|> Account


'Observer pattern for notifiyer
interface Subject
Interface Observer
class EmailObserver

Observer --> Subject
EmailObserver ..|> Observer

AccountServiceApplicationFactory --> Subject

abstract class InterestState {
    +getInterest();
}
class SavingInterestLowState
class SavingInterestMidState
class SavingInterestHighState
SavingInterestHighState ..|> InterestState
SavingInterestLowState ..|> InterestState
SavingInterestMidState ..|> InterestState

InterestState <-* Account
AccountServiceApplicationFactory ..|> AccountService
AccountServiceImpl --|> AccountServiceApplicationFactory
CCardServiceImpl --|> AccountServiceApplicationFactory

AccountServiceApplicationFactory ..> StorageFactory
Account <-- AccountServiceApplicationFactory

@enduml